[book]
authors = ["Lachezar Lechev"]
language = "en"
multilingual = false
src = "src"
title = "AeroRust 🚀🦀 - Aerospace & Rust"
description = "Community Working group working in Aerospace with the Rust programming language"

[output.markdown]

[preprocessor.links]

renderers = ["html"]
preferred-dark-theme = ""

[preprocessor.index]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
# no-section-label = false
git-repository-url = "https://github.com/AeroRust/AeroRust.github.io"
git-repository-icon = "fa-github"

[output.html.fold]
enable = false
level = 1

[output.html.playpen]
editable = false
copyable = true
copy-js = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 15
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
