# The URL the site will be built for
base_url = "https://aerorust.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
github_repo = "https://github.com/AeroRust/aerorust.github.io"
github_propose_blog_post = "https://github.com/AeroRust/AeroRust.github.io/issues/new?assignees=&labels=blog-post&template=featured-blog-post.md&title=%5BBlog+post%5D"
github_org = "https://github.com/AeroRust"
discord_invite = "https://discord.gg/6wFvsFWfnu"
discord_members_count = "400+"
rustlang_website = "https://rust-lang.org"
twitter_username = "@AeroRust"
twitter_url = "https://twitter.com/AeroRust"
youtube_url = "https://youtube.com/c/AeroRust"
email = "aerospace.rust@gmail.com"